## 母集団分布と標本分布

### 前回の復習

-   不偏分散の式

$$
s^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2
$$

```{r}
x <- seq(20, 40, 0.1)
y <- dnorm(x, mean=30, sd=4)  # N(30, 16)
plot(x, y, type="l")

```

------------------------------------------------------------------------

-   標本平均や不偏分散など、標本統計量の分布を標本分布と呼ぶ\
-   標本分布は、母集団分布の種類、標本統計量の種類、サンプルサイズによって決まる\
-   確率変数である「標本のデータ」から計算される「標本統計量」もまた確率変数である

------------------------------------------------------------------------

-   標本分布は、標本統計量（標本平均など）の確率分布です。\
-   ※標本に含まれる個別のデータの分布ではありません。

------------------------------------------------------------------------

## サンプルコード：ミニトマトの母集団分布と標本分布

-   母集団分布: N(30, 16)
    -   母平均: 30\
    -   母分散: 16\
    -   母標準偏差: 4
-   ここから、サンプルサイズ 4 の標本を無作為抽出します\
-   作成した標本から標本平均を算出します

------------------------------------------------------------------------

```{r}
# 母集団
mu <- 30      # 母平均
sigma <- 4    # 母標準偏差
tomato_population <- rnorm(100000, mean=mu, sd=sigma)
tomato_population
```

```{r}
mu<-30
sigma<-4
tomato_population<rnorm(100000,mean=mu,sd=sigma)
tomato_sample_means<-numeric(1000)
tomato_sample_size<-4
for(i in 1:1000){
  tomato_sample_means[i]<-mean(sample(tomato_population,tomato_sample_size))
}
tomato_sample_means
hist(tomato_popution,xlim=c(10,50),breaks=seq(0,50,1))
```

------------------------------------------------------------------------

### 標本分布に関係する2つの用語

#### 標準誤差: Standard Error: SE

-   標本統計量の標準偏差のこと

#### 不偏性

-   推定量の期待値が母数の値と一致すること\
-   標本分布の平均が母数と一致すること

### 応用: データの標準化と標準正規分布

$$
N(\mu, \frac{\sigma^2}{n})
$$

------------------------------------------------------------------------

- データの標準化  
  - 標準化: 平均を引いて、標準偏差で割る  
  - そうすると \( N(0, 1) \) の分布に従うようになる  

$$
z = \frac{\bar{x} - \mu}{\sigma / \sqrt{n}} \sim N(0, 1)
$$

```{r}
# 母集団
mu <- 30
sigma <- 4
tomato_population <- rnorm(100000, mean=mu, sd=sigma)
tomato_population

# 1000回、サンプルサイズ1の標本をつくる
tomato_sample_size <- 1
tomato_samples <- numeric(1000)

for (i in 1:1000) {
  tomato_samples[i] <- sample(tomato_population, tomato_sample_size)
}

tomato_samples

```



