# Rの文字列操作

-   Rには文字列ベクトルを操作する関数が用意されている

### 主な文字列操作関数

| 関数名           | 処理内容                           |
|:-----------------|:-----------------------------------|
| nchar            | 文字列の長さを取得する             |
| toupper, tolower | 文字列を大文字（小文字）に変換する |
| substr           | 部分文字列を取得する               |

#nchar 関数」 -nchar関数,第一引数で受け取った文例べべ

```{r}
x<-c("one","two","three")
nchar(x)

```

```{r}
x<-c("one","two","three")
toupper(x)

```

```{r}
x<-c("one","two","three")
substr(x,2,3)

```

```{r}
x <- c("one", "two", "three")

grep("t", x)  # "t"が含まれている要素番号を返す
grep("^o", x) # 先頭を意味する、1文字目がoの要素番号を返す
grep("o$", x) # 末尾を意味する、最後の文字がoの要素番号を返す
grep("e{2}", x) # "e"が2回続く要素の要素番号を返す


```

### 正規表現で覚えておくといいもの

-   \^A : 行頭文字が“A”
-   A\$ : 行末文字が“A”
-   A{3} : “A”が3回繰り返す、つまり“AAA”
-   \^A+ : “A”が1回以上繰り返す、“A”や“AA”、“AAAA”



```{r}
x<-c("one","two","three")
sub("e","T",x)

```
#Paste
```{r}
paste(c("one"), c("two")) # 文字列ベクトルを1つの文字列 "one two" に連結する

paste(c("one"), c("two"), sep = ",") # "one,two"

paste(c("one", "three"), c("two", "four"), sep=",") # "one,two" "three,four"

```