# 確率

- 確率とは、事象の起こりやすさを定量的に表現したもの
- ここでは、確率について記号 P を使って記述する方法を学習する
- 確率の定義には、いくつかのアプローチがある
  - 先験的確率
  - 経験的確率
  - 主観的確率
  - 確率の公理
# 確率の記述方法

- サイコロを振って1が出る事象をXとする
- 事象Xの起こる確率

$$
X = \{1\} \\\
P(X) = \frac{1}{6}
$$
>probability

$$
X=\{1,3,5\}\\\
p(X)=\frac{3}{6}=\frac{1}{2}\\\
X \cap Y={1,3}\\\

p(X\cap Y)=\frac{2}{6}=\frac{1}{3}
$$
$$
P(A) = \frac{R}{N} \\
N: 全事象の根元事象の数 \\
R: 事象Aの根元事象の数
$$
### 確率の定義2. 経験的確率

- たとえばイカサマのサイコロがある場合、1の目の出る確率は実際に振ってみないとわからない
- 繰り返し何度もサイコロを振ることで、1の目の出る確率を求めることができる
- たとえば100回サイコロを振って、1の目が50回出た場合、1の目の出る確率は50/100と推測できる


```{r}
# 1が50%ででるサイコロ
dice_prob = c(0.5, 0.1, 0.1, 0.1, 0.1, 0.1)
dice <- sample(1:6, size = 100, prob = dice_prob, replace = T)
table(dice)
```
### 確率の定義3. 主観的確率

- 先験的確率、経験的確率は、誰が計算しても同じ結果になる（客観的確率ともいう）
- 上記のアプローチが取れない場合、分析者が対象に対して主観的に確率を与えて分析を行う手法がある

### 確率の定義4. 確率の公理

- あるゆる事象Aに対して、0 <= P(A) <= 1 である
- P(Ω) = 1 である
  - Ω: 全事象
- 排反な事象A1, A2, A3...に対して、
  - P(A1∪A2∪A3) = P(A1) + P(A2) + P(A3)...

## エクササイズ

- 2枚のコイン投げ、という試行において、表をT、裏をFとしたとき、標本空間を以下の様に定義しました。

Ω = {(T, T), (T, F), (F, T), (F, F)}

- このとき、少なくとも1回は表が出る事象Aを以下の様に定義します。

A = {(T, T), (T, F), (F, T)}

この事象Aの確率は以下の様に記述します。

P(A)=3/4

- 少なくとも1回は裏が出る事象Bの確率を求めてください
  B = {(T, F), (F, T), (F, F)}
  P(B) = 3/4

- 表が2回でる事象Cの確率を求めてください
  C = {(T, T)}
  P(C) = 1/4

- 事象Aの補事象を事象Dとします。事象Dの確率を求めてください
  D = {(F, F)}
  P(D) = 1/4


